spring.application.name=app-genIA
spring.data.mongodb.database=app-genIA-db
spring.data.mongodb.port=27017
de.flapdoodle.mongodb.embedded.version=5.0.5

# Persistent storage directory
spring.mongodb.embedded.storage.databaseDir=./data/mongodb
